### ISSUE TITLE
compile problem in linux

### ISSUE THREAD

**Issue by shoaib-mi** [vanyle/SublimeNim#11]
Hi. I tried it on both Linux and Windows. on Windows it works good, but in linux it does not compile it via `ctrl+b`. it only compile the code through `Tools -> Build with Nim`.

**Comment by vanyle** [comment]
How does your *Key Bindings* file look like ?
You are compiling a project (with nimble) or just a file (with nim) ?

**Comment by shoaib-mi** [comment]
pressing `ctrl+b` or selecting `Tools -> packages -> sublimenim -> compile and run current file ` after opening sublimetext has the same output:
       
        Nim Compiler Version 1.6.4 [Linux: amd64]
        Compiled at 2022-02-10
        Copyright (c) 2006-2021 by Andreas Rumpf
        ::
        
        nim command [options] [projectfile] [arguments]
        
and the rest of the output when you only run `nim` in terminal.

after that if I press `ctrl+b` again, in status bar I see `checking program validity` and then nothing happens. Autocomplete does not work either.

here is the key binding 
            
            [
	            {
		            "keys":["ctrl+b"],
		            "command":"run_nim",
		            "context":[
			            {
				            "key":"selector",
				            "operator":"equal",
				            "operand":"source.nim"
			            }
		            ]
	            },
	            {
		            "keys":["ctrl+shift+b"],
		            "command":"run_nimble",
		            "context":[
			            {
				            "key":"selector",
				            "operator":"equal",
				            "operand":"source.nim"
			            }
		            ]
	            },
	            
	            {
		            "keys": ["ctrl+alt+p"],
		            "command":"prettify_nim",
		            "context":[
			            {
				            "key":"selector",
				            "operator":"equal",
				            "operand":"source.nim"
			            }
		            ]
	            },
            
            
	            // Some other commands you might want to assign to a key.
	            
	            // Run in release mode
	            /*
	            {
		            "keys":["ctrl+alt+b"],
		            "command":"run_nim",
		            "args":{
			            "arguments":["-d:release","-d:danger"]
		            },
		            "context":[{"key":"selector","operator":"equal","operand":"source.nim"}]
	            },
	            */
	            // Run in release mode for nimble
	            /*
	            {
		            "keys":["ctrl+alt+b"],
		            "command":"compile_nimble",
		            "args":{
			            "arguments":["-d:release","-d:danger"]
		            },
		            "context":[{"key":"selector","operator":"equal","operand":"source.nim"}]
	            },
	            */
            
            
	            // Quickly open documentation
	            /*
	            {
		            "keys":["ctrl+alt+o"]
		            "command":"open_document_nim",
		            "context":[{"key":"selector","operator":"equal","operand":"source.nim"}]
	            },
	            */
            
	            
            
            ]

I am compiling one file which contains one line of code `echo "Hello World"`.

**Comment by vanyle** [comment]
Ok, from what I understand, there are 2 causes.
The first is that `subprocess.Popen` does not behave in exactly the same way on Window and Linux and the other is that there is a bunch of `.exe` in the code that make highly non-portable.

I'll commit a fix for this when I get some time. Sorry for the inconvenience, I did not test the plugin for linux as it's not my main os.

**Comment by vanyle** [comment]
The plugin should now work on Linux. This includes:
- `Ctrl+B` for building
- Nim check messages
- Nim suggest tooltips.

Reopen this issue if you find that it is not working.

**Comment by lf-araujo** [comment]
Not reopening, but I am finding something that is related. Nimplus is not finding Nim in the path, possibly related  to the way I installed subl in my system (I am using an arch installer in my base system, which is Solus). 

Anyway, I get:

```
[Errno 2] No such file or directory: 'nim'
[cmd: ['nim', 'r', '/home/luis/Documents/OneDrive/Coding/Nim/Programs/allocator/src/allocator.nim']]
[dir: /home/luis/Documents/OneDrive/Coding/Nim/Programs/allocator/src]
[path: /home/luis/.local/bin:/home/luis/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin:/snap/bin]
[Finished]
```

- Is there a way I could set the environment in the keymap config?

```
{
	"keys":["ctrl+b"],
	"command":"run_nim",
	"context":[
		{
			"key":"selector",
			"operator":"equal",
			"operand":"source.nim",
    "env": "/home/luis/.nimble/bin",
		}
	]
},
```

Or perhaps setting nims full path somewhere?

**Comment by vanyle** [comment]
Does `nim` work properly from the command line otherwise ?
The `nim` executable (and related executables like nimsuggest) should be in your path.

**Comment by shoaib-mi** [comment]
I am not sure how to define environmental variables in Linux, and how to give the path in sublime. But I can compile nim via terminal just by using `nim c myfile.nim`. So at least terminal knows where is nim and nimble are located.

**Comment by lf-araujo** [comment]
Thank you for taking the time. 

I reinstalled sublime using snap package instead of the weird installation option I had. My nim installation is functional in the terminal, but opening sublime from the menu and using NimPlus results in NimPlus not finding nim binaries.


Now, and this is interesting, running sublime from the terminal (where the path is properly picked up), works as expected. 

Setting the path for nim binaries in nimplus configuration would certainly fix this.
