### ISSUE TITLE
can't see highlight errors

### ISSUE THREAD

**Issue by geohuz** [vanyle/SublimeNim#12]
I just download and installed sublimetext 4 and install the nimplus package, the syntax highlight is ok, but I don't see any error being highlighted, is there anything wrong from my side? I'm using macos ventura 13.1

**Comment by vanyle** [comment]
First, make sure `"nimplus.savecheck"` is set to `true` in your `Preferences: NimPlus` file.
Also, check that:
- The `nim check <filename>` command, which is used behind the scenes to find errors, is available and works.
- When saving, at the bottom bar, the message "Checking program validity" is displayed.
- When opening the sublime console `View > Show Console`, are any errors related to NimPlus displayed ?

Errors are supposed to be underlined with a red squiggly line. Warnings are the same with a blue line.

Finally, I must say that I never tested the plugin on Mac, only on linux and windows, so it might have something to do with this.

**Comment by geohuz** [comment]
@vanyle thanks for the reply, I've confirmed the following things:

1. ``nim check`` runs normally and it returns check errors on nim file
2. There is no "checking program validity" displayed
3. Show console seems ok, no relative error for NimPlus

and here is the NimPlus settings:

```
{
    // Run nim check when saving the file ?
    "nimplus.savecheck": true,
    // Autocomplete support ? (based on nimsuggest)
    "nimplus.autocomplete": true,
    // Provide description when hovering over symbols (based on nim suggest)
    "nimplus.hoverdescription": true,

    // Arguments to prepend to the nim build commands.
    // This can be used to specify a console, for example using: "wt","--window","0" on windows terminal.
    "nimplus.nim.console": [],
    "nimplus.nimble.console": [],

    // Arguments passed to the nim compiler when building / checking the file
    // The path to the current file is appended at the end.
    // You can add here --d:release and --d:danger when needed
    "nimplus.nim.arguments": ["--threads:on","-d:ssl","--stdout:on"],

    "nimplus.nim.save_before_build": true,
    "nimplus.nimble.save_before_build": true,

    // Set to true if you have terminus install and want to enjoy the integration with it.
    // The output is not displayed in the output panel anymore in this case.
    // Terminus allows you to interact the the stdin of your program which is nice when developping command line applications
    "nimplus.use_terminus": false
}
```

**Comment by geohuz** [comment]
It is my problem of installed several different sublimtext version. Thanks!
