### ISSUE TITLE
Use the sbnf for the syntax definition

### ISSUE THREAD

**Issue by vanyle** [vanyle/SublimeNim#6]
Currently, the syntax from NimLime is used. It would be nice to have proper syntax highlighting that is provably correct.

We can use this syntax file compiler for this: https://github.com/BenjaminSchaaf/sbnf
We just need to translate this: https://nim-lang.org/docs/manual.html#syntax-grammar into something compatible with sbnf. (It might already be compatible, I haven't look deeply into it.)

**Comment by AmjadHD** [comment]
It's not possible, there is no way to reliably represent indented blocks in sublime-syntax and by consequence sbnf.

**Comment by vanyle** [comment]
😢 Closing the issue.
